name: Run on EC2 Self-hosted Runner

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show content
        run: cat newfile.txt

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Scan with Trivy
        run: trivy fs . --exit-code 0 --severity HIGH,CRITICAL

      - name: Run your custom code
        run: |
          echo "Running your logic from newfile.txt"