name: Lint, Format & Security Scan

on:
  push:
    branches: [main]

jobs:
  quality-and-security:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run Linter
      - name: Run Lint (ESLint)
        run: npm run lint

      # Run Formatter (Prettier)
      - name: Format Code (Prettier)
        run: npx prettier . --check

      # Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      # Scan Codebase for vulnerabilities
      - name: Run Trivy Filesystem Scan
        run: trivy fs . --exit-code 0 --severity HIGH,CRITICAL