name: Run on EC2 Self-hosted Runner

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show newfile.txt content
        run: cat newfile.txt

      - name: Wait for apt lock (if needed)
        run: |
          while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
            echo "Waiting for other apt process to finish..."
            sleep 5
          done

      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends wget gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends trivy

      - name: Scan with Trivy
        run: trivy fs . --exit-code 0 --severity HIGH,CRITICAL

      - name: Deploy (Mock Step)
        run: echo "✅ Code scanned and ready to deploy!"