name: Trivy Scan & Optional Auto Push

on:
  push:
    branches: [main]

jobs:
  scan-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Run Trivy Filesystem Scan
        run: trivy fs . --exit-code 0 --severity HIGH,CRITICAL

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit and Push Changes
        env:
          TOKEN: ${{ secrets.TO_TEST }}
        run: |
          git add .
          git diff --cached --quiet || git commit -m "🤖 Auto-update from GitHub Actions"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD:main